audit_header: false
title: Stafford/Fredericksburg Real Estate Video Blog with The Gillies Team
description: Our mission at RE/MAX Real Estate Connections is to be your best resource for Stafford/Fredericksburg real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The RE/MAX Real Estate Connections, your professional Stafford/Fredericksburg Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Testimonials
    url: /testimonials/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: The Gillies Team
  title:
  license_number:
  about_markdown: |
    <strong>REAL ESTATE DONE DIFFERENTLY</strong><br>
    Ranked as the top real estate team in the Stafford/Fredericksburg area, Michael and his team of real estate advisers have sold over $400 million dollars in real estate. We know the real estate experience can be daunting which is why we have developed a proven process creating a simpler, hassle-free experience with open lines of communication.

    At the Gillies Team, our #1 priority is to provide a convenient, consistent world class experience 100% of the time.

    Too many people come to us after becoming frustrated, feeling like they are going at it alone with no idea what was coming around the next bend. We believe you should be feeling confident and informed every step of the way. You should know what to expect and get what's expected. For this reason we have chosen to do real estate differently.

    <strong>What makes us different?</strong>

    <strong>GUARANTEE PROGRAMS</strong><br>
    We want you to feel secure so we eliminate the risk.

    <strong>INDIVIDUAL STRATEGY PLANS</strong><br>
    We listen to each individual need and make recommendations based on what's best for our client. We base every decision on what's best for our client.

    <strong>SUPPORT & COMMUNICATION PLAN</strong><br>
    Our team of specialists provide minute to minute support and communication. From our buyer and listing specialist teams to our in-office marketing, contract processing, client care, sales manager and finance members, we ensure all I's are dotted and T's are crossed. We cater to needs you didn't even know you had.

    <strong>HASSLE FREE</strong><br>
    Your time is valuable. You should not be the one doing the job of a real estate agent. Our proactive approach predicts, avoids and absorbs bumps in the road so you can focus on the most important things in your life.

    <strong>So, let us take the weight off your shoulders. That's what we do best.</strong>
  brand: RE/MAX Real Estate Connections
  brokerage:
  market: Stafford/Fredericksburg
  address: 85 Mine Rd., Ste. 101<br>Stafford, VA 22554
  phone: 540-300-1582
  phone_type:
  phone2:
  phone2_type:
  email: Info@GilliesTeam.com
  url: http://GilliesTeam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.staffordfredericksburghomesearch.com/homevalue/StaffordVA
  second_CTA_text: Home Search
  second_CTA_URL: http://www.staffordfredericksburghomesearch.com/search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Stafford/Fredericksburg Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.staffordfredericksburghomesearch.com/homevalue/StaffordVA

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Stafford/Fredericksburg Home?"
    CTA_text2: "Search the entire MLS for your Stafford/Fredericksburg home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.staffordfredericksburghomesearch.com/search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/GilliesTeam/
  linkedin_url: https://www.linkedin.com/in/cindygillies
  youtube_url: https://www.youtube.com/channel/UChdufbIqDiGCzzKAWgdcRUA
  twitter_url: https://twitter.com/gilliesteam
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/The-Gillies-Team/
  trulia_url: http://www.trulia.com/profile/the-gillies-team-agent-stafford-va-zgxlb4k8/overview
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/northern-virginia-real-estate/id1093546323?mt=2

podcast:
  title: 'Stafford/Fredericksburg Real Estate Podcast with The Gillies Team'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Stafford/Fredericksburg Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from RE/MAX Real Estate Connections - your professional Stafford/Fredericksburg Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Stafford/Fredericksburg, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'The Gillies Team'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Stafford/Fredericksburg Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#ea324f'
  theme_color: '#083f88'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(238,238, 238, 1)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
